name: 'Check-Job-Creation'
description: 'Creates a github-actions check-job'
outputs:
  check_id:
    description: "ID of the created check"
    value: ${{ steps.create_check.outputs.check_id }}
runs:
  using: 'composite'
  steps:
  - name: Creating the check
    id: create_check
    shell: bash
    env:
      ACT_RUN: 'if [ "${ACT}" ] && [ "${ACT_OVERRIDE:-"false"}" == "false" ]; then echo "NOTICE: step is running via ACT - skipping"; exit 0; fi;'
      PR_SHA: "${{github.event.pull_request.head.sha}}"
      GH_RUN_ID: "${{ github.run_id }}"
      GITHUB_TOKEN: "${{ github.token }}"
      GITHUB_REPOSITORY: "${{ github.repository }}"
      WORKFLOW_NAME: "${{ github.workflow }}"
    run: |
      # Checking run under ACT with override option
      eval "${ACT_RUN}"

      echo '::group::Creating new check'
      curl -vf -POST \
        --retry 5 \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/check-runs" \
        -d '
          {
            "name":        "${{env.check_name}}",
            "head_sha":    "${{env.PR_SHA}}",
            "status":      "in_progress",
            "external_id": "${{env.GH_RUN_ID}}",
            "output": {
                        "title":   "${{ env.WORKFLOW_NAME }} running",
                        "summary": "pending check for commit ${{env.PR_SHA}}",
                        "text":    "Awaiting check result..."
            }
          }
        ' \
        -o new_check.json

      id=$(jq -r '.id' new_check.json)

      if [ -z "${id}" ]; then
        echo "ERROR: Failed to create the required check job"
        echo "Result of curl:"
        cat new_check.json
        exit 1
      fi
      echo "::endgroup::"

      echo "Id is: ${id}"
      echo "::set-output name=check_id::${id}"

