name: 'Check-Job-Creation'
description: 'Creates a github-actions check-job'
inputs:
  pending_check:
    required: true
    description: action to execute - [ create, verify ]
runs:
  using: 'composite'
  steps:
  - name: Creating the check
    shell: bash
    env:
      ACT_RUN: 'if [ "${ACT}" ] && [ "${ACT_OVERRIDE:-"false"}" == "false" ]; then echo "NOTICE: step is running via ACT - skipping"; exit 0; fi;'
      PR_SHA: "${{github.event.pull_request.head.sha}}"
      GH_RUN_ID: "${{ github.run_id }}"
      GITHUB_TOKEN: "${{ github.token }}"
      GITHUB_REPOSITORY: "${{ github.repository }}"
      WORKFLOW_NAME: "${{ github.workflow }}"
      PENDING_CHECK: "${{ inputs.pending_check }}"

    run: |
      # Checking run under ACT with override option
      eval "${ACT_RUN}"
      set -euo pipefail

      if [ "${{ env.PENDING_CHECK }} == "create" ]; then
        echo "executing create"
      elif [ "${{ env.PENDING_CHECK }}" == "verify" ]; then
        echo "executing verify"
      else
        echo "ERROR: invalid action ${{ env.PENDING_CHECK }} for pending check. Allowed: create or verify"
        exit 1
      fi


