name: 'Submit succes conclusion'
description: 'Sends a PATCH payload to an awaiting check'
inputs:
  check_id:
    description: "ID of the created check"
    required: true
runs:
  using: 'composite'
  steps:
  - name: Submit successful check completion
    shell: bash
    env:
      ACT_RUN: 'if [ "${ACT}" ] && [ "${ACT_OVERRIDE:-"false"}" == "false" ]; then echo "NOTICE: step is running via ACT - skipping"; exit 0; fi;'
      GITHUB_TOKEN: "${{ github.token }}"
      GITHUB_REPOSITORY: "${{ github.repository }}"
      CHECK_ID: "${{ inputs.check_id }}"
    run: |
          # Checking run under ACT with override option
          eval "${ACT_RUN}"

          echo "Sending success conclusion to the check"
          curl -sf -X PATCH \
            --retry 5 \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/check-runs/${{ env.CHECK_ID }}" \
            -d '
              {
                "name": "${{ env.check_name }}",
                "conclusion": "success"
              }
            '
