---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-test
    tag: main

params:
  TARGETS:

inputs:
- name: release

outputs:
- name: release  

run:
  path: release/ci/autoscaler/tasks/make/make.sh
