---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-test
    tag: main

params:
  TARGETS:

inputs:
- name: release
- name: ci

outputs:
- name: release  

run:
  dir: release