---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-deploy
    tag: main

inputs:
- name: bbl-state
- name: ci
- name: prometheus-boshrelease

run:
  path: ci/ci/infrastructure/scripts/deploy-prometheus.sh
