name: 'Acceptance Tests Common'
description: 'Common steps for all acceptance tests'
runs:
  using: "composite"
  steps:
    - uses: ./app-autoscaler-release/.github/actions/setup_go
      with:
        source: app-autoscaler-release/src/autoscaler
    - uses: ./app-autoscaler-release/.github/actions/setup_java
      with:
        version: 11

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Cli Cache
      uses: actions/cache@v3
      with:
        path: |
          "${{ env.HOME }}/bin/"
        key: ${{ runner.os }}-deploy_cli-${{ hashFiles( '${{ env.AUTOSCALER_DIR }}/.github/workflows/install_cli.sh' ) }}

    - name: Install deployment ClIs
      shell: bash      
      run: "${AUTOSCALER_DIR}/.github/workflows/install_cli.sh"

    - name: clone BBL repo
      uses: actions/checkout@v3
      with:
        repository: cloudfoundry/app-autoscaler-env-bbl-state
        ssh-key: ${{ secrets.BBL_SSH_KEY }}
        path: bbl

    - name: clone CI repo
      uses: actions/checkout@v3
      with:
        repository: cloudfoundry/app-autoscaler-ci
        ssh-key: ${{ secrets.BBL_SSH_KEY }}
        path: ci
