# This ops file is used to change the deployment ID of the bosh deployment to enable multiple deployments
# with different dns names (independent name spaces)
# Parameters:
# deployment_name: Unique deployment name.
---

# Change the Public dns names to be unique for the deployment
- type: replace
  path: /instance_groups/name=asapi/jobs/name=route_registrar/properties/route_registrar/routes/name=api_server/uris
  value: [ ((deployment_name)).((system_domain)) ]

- type: replace
  path: /instance_groups/name=asapi/jobs/name=route_registrar/properties/route_registrar/routes/name=autoscaler_service_broker/uris
  value: [ ((deployment_name))servicebroker.((system_domain)) ]

- type: replace
  path: /instance_groups/name=asapi/jobs/name=route_registrar/properties/route_registrar/routes/name=autoscaler_metrics_forwarder/uris
  value: [ ((deployment_name))metrics.((system_domain)) ]

- type: replace
  path: /instance_groups/name=asapi/jobs/name=route_registrar/properties/route_registrar/routes/name=autoscaler_metricsforwarder_health/uris
  value: [ ((deployment_name))-metricsforwarder.((system_domain)) ]

#TODO
#- type: replace
#  path: /variables/name=metricsserver_server/options/alternative_names
#  value:
#    - *metricsserver_domain
#    - "*.asmetrics.default.app-autoscaler.bosh"