---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-deploy
    tag: main

params:
  SYSTEM_DOMAIN:
  NAME_PREFIX: ASATS
  NODES: 3
inputs:
- name: app-autoscaler-release
- name: bbl-state

outputs:

run:
  path: app-autoscaler-release/ci/autoscaler/scripts/run-acceptance-tests.sh
