---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ghcr.io/cloudfoundry/app-autoscaler-ci-test
    tag: master

inputs:
- name: app-autoscaler-release
- name: app-autoscaler-ci

run:
  path: app-autoscaler-ci/autoscaler/scripts/run-integration-tests.sh
