name: Acceptance Tests - Buildin
on:
  pull_request:
    types: [ opened, labeled, synchronize ]
    paths:
     - 'src/acceptance/**'

concurrency:
  group: acceptance_buildin-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  BUILDIN_MODE: "true"
  SERVICE_OFFERING_ENABLED: "false"
  DEPLOYMENT_NAME: "autoscaler-buildin-${{ github.event.pull_request.number }}"

jobs:
  acceptance_tests_reusable:
    name: " " # Whitespace name looks nicest on Github UI
    uses: ./.github/workflows/acceptance_tests_reusable.yaml
    with:
      suites: "[ 'API', 'APP' ]"
    secrets:
      bbl_ssh_key: "${{ secrets.BBL_SSH_KEY }}"
