name: Acceptance Tests
on:
  pull_request:
jobs:
  acceptance_test:
    name: run the acceptance test for a PR
    runs-on: ubuntu-latest
    env:
      MAVEN_VERSION: 3.6.3
      MAVEN_SHA: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
      DEPLOYMENT_NAME: "app-autoscaler-${{ github.event.pull_request.number }}"
      SERVICE_BROKER_NAME: "app-autoscaler-${{ github.event.pull_request.number }}servicebroker"
      SERVICE_NAME: "autoscaler-${{ github.event.pull_request.number }}"
      BBL_STATE_PATH: "${{ github.workspace }}/bbl/bbl-state"

      AUTOSCALER_DIR: "${{ github.workspace }}/app-autoscaler-release"
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      - uses: ./app-autoscaler-release/.github/actions/setup_go
        with:
          source: app-autoscaler-release/src/autoscaler
      - uses: ./app-autoscaler-release/.github/actions/setup_java
        with:
          version: 11

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Cli Cache
        uses: actions/cache@v3
        with:
          path: |
            "${{ env.HOME }}/bin/"
          key: ${{ runner.os }}-deploy_cli-${{ hashFiles( '${{ env.AUTOSCALER_DIR }}/.github/workflows/install_cli.sh' ) }}

      - name: Install deployment ClIs
        run: "${AUTOSCALER_DIR}/.github/workflows/install_cli.sh"

      - name: clone BBL repo
        uses: actions/checkout@v3
        with:
          repository: cloudfoundry/app-autoscaler-env-bbl-state
          ssh-key: ${{ secrets.BBL_SSH_KEY }}
          path: bbl

      - name: clone CI repo
        uses: actions/checkout@v3
        with:
          repository: cloudfoundry/app-autoscaler-ci
          ssh-key: ${{ secrets.BBL_SSH_KEY }}
          path: ci

      - name: run update
        run: cd ${AUTOSCALER_DIR}; ./scripts/update

      - name: deploy autoscaler
        run: |
         export OPS_FILES="${AUTOSCALER_DIR}/example/operation/loggregator-certs-from-cf.yml\
          ${AUTOSCALER_DIR}/example/operation/add-extra-plan.yml\
          ${AUTOSCALER_DIR}/example/operation/set-release-version.yml\
          ${AUTOSCALER_DIR}/example/operation/enable-name-based-deployments.yml"
         export BBL_STATE_PATH="${GITHUB_WORKSPACE}/bbl/bbl-state"
         ${GITHUB_WORKSPACE}/ci/autoscaler/scripts/deploy-autoscaler.sh

      - name: register autoscaler broker
        run: ${GITHUB_WORKSPACE}/ci/autoscaler/scripts/register-broker.sh

      - name: run acceptance tests
        run: |
          export SYSTEM_DOMAIN=autoscaler.ci.cloudfoundry.org
          export SERVICE_OFFERING_ENABLED=true
          export SKIP_SSL_VALIDATION=true
          export NAME_PREFIX=ASATS
          export SUITES=api #"api app broker"
          export NODES=3
          export 
          ${GITHUB_WORKSPACE}/ci/autoscaler/scripts/run-acceptance-tests.sh

      - name: Cleanup deployments
        if: always()
        run: |
          echo TODO
          exit 1