name: Acceptance Tests (Buildin)
on:
  pull_request:
    types: [ opened, labeled, synchronize ]
    paths:
      - 'src/acceptance/**'

env:
  MAVEN_VERSION: 3.6.3
  MAVEN_SHA: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
  BUILDIN_MODE: true
  SERVICE_OFFERING_ENABLED: false
  check_name: "acceptance-test-check-buildin"
  PR_NUMBER: "${{ github.event.pull_request.number }}"
  DEPLOYMENT_NAME: "autoscaler-${{ github.event.pull_request.number }}"
  SERVICE_BROKER_NAME: "autoscaler-${{ github.event.pull_request.number }}servicebroker"
  SERVICE_NAME: "autoscaler-${{ github.event.pull_request.number }}"
  BBL_STATE_PATH: "${{ github.workspace }}/bbl/bbl-state"
  NAME_PREFIX: "autoscaler-${{ github.event.pull_request.number }}-TESTS"
  GINKGO_OPTS: "--fail-fast"
  NODES: 3
  AUTOSCALER_DIR: "${{ github.workspace }}/app-autoscaler-release"
  CI_DIR: "${{ github.workspace }}/app-autoscaler-release/ci"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  acceptance_pending_check:
    outputs:
      check_id: ${{ steps.create_check.outputs.check_id }}
    # Determine if we require to run Acceptance Tests jobs in this workflow by checking relevant events and labels.
    # Finalisation job runs always since we use branch protection rule for acceptance tests.
    if: |
      ( ( github.event.action == 'opened' || github.event.action == 'synchronize' )
          && ( contains(github.event.pull_request.labels.*.name, 'allow-acceptance-tests') || contains(github.event.pull_request.labels.*.name, 'dependencies') )
      ) ||
      (  ( github.event.action == 'labeled' )
          && ( github.event.label.name == 'allow-acceptance-tests' ||  github.event.label.name == 'dependencies' )
      )
    name: Create pending check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      - name: "Create the check"
        uses: ./app-autoscaler-release/.github/actions/pending_check-create

  deploy_autoscaler:
    needs: [ acceptance_pending_check ]
    name: Deploy autoscaler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      # TODO: unhashme
      # - uses: ./app-autoscaler-release/.github/actions/acceptance_setup
      #   with:
      #     ssh-key: ${{ secrets.BBL_SSH_KEY }}
      - name: deploy autoscaler
        run: |
          echo ">> WIP: exiting early"; exit 1
          cd ${{ env.AUTOSCALER_DIR }}
          make deployment


  acceptance_tests:
    needs: [ deploy_autoscaler ]
    strategy:
      matrix:
        suite: [ API, APP ]
    runs-on: ubuntu-latest
    name: ${{ matrix.suite }} acceptance tests
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      # TODO: unhashme
      # - uses: ./app-autoscaler-release/.github/actions/acceptance_setup
      #   with:
      #     ssh-key: ${{ secrets.BBL_SSH_KEY }}
      - name: run acceptance test - api
        run: |
          echo ">> WIP: exiting early"; exit 0
          cd ${{ env.AUTOSCALER_DIR }}
          make acceptance-tests SUITES="${{ matrix.suite }}"

  # acceptance_test_api:
  #   needs: [ deploy_autoscaler ]
  #   name: API acceptance tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         path: app-autoscaler-release
  #     # TODO: unhashme
  #     # - uses: ./app-autoscaler-release/.github/actions/acceptance_setup
  #     #   with:
  #     #     ssh-key: ${{ secrets.BBL_SSH_KEY }}
  #     - name: run acceptance test - api
  #       run: |
  #         echo ">> WIP: exiting early"; exit 0
  #         cd ${{ env.AUTOSCALER_DIR }}
  #         make acceptance-tests SUITES="api"

  # acceptance_test_app:
  #   needs: [ deploy_autoscaler ]
  #   name: APP acceptance tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         path: app-autoscaler-release
  #     # TODO: unhash me
  #     # - uses: ./app-autoscaler-release/.github/actions/acceptance_setup
  #     #   with:
  #     #     ssh-key: ${{ secrets.BBL_SSH_KEY }}
  #     - name: run acceptance test - app
  #       run: |
  #        echo ">> WIP: exiting early"; exit 0
  #        cd ${{ env.AUTOSCALER_DIR }}
  #        make acceptance-tests SUITES="app"

  acceptance_jobs_verify:
    #This job submits success result to the awaiting check only if all depended jobs have passed
    needs: [ acceptance_pending_check, deploy_autoscaler, acceptance_tests ]
    name: Tests conclusion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      - name: "Send succes to awaiting check"
        uses: ./app-autoscaler-release/.github/actions/pending_check-conclusion
        with:
          check_id: ${{ needs.acceptance_pending_check.outputs.check_id }}


  deployment_cleanup:
    needs: [ acceptance_jobs_verify ]
    name: Cleanup deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      - uses: ./app-autoscaler-release/.github/actions/acceptance_setup
        with:
          ssh-key: ${{ secrets.BBL_SSH_KEY }}
      - run: |
          cd ${{ env.AUTOSCALER_DIR }}
          make deployment-cleanup


  acceptance_tests_finalise:
    needs: [ acceptance_jobs_verify ]
    if: ${{ always() }}
    name: Tests Finalise (Buildin)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      - name: "Create check report"
        uses: ./app-autoscaler-release/.github/actions/pending_check-finalise
        with:
          check_filter: ".*acceptance tests"


