name: bosh-release
on:
  pull_request:
  workflow_dispatch:  
jobs:
  bosh-release:
    name: Build Autoscaler Components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Dev Release
        uses: garethjevans/bosh-release-action@v1.0.2
