name: generate
on:
  pull_request:
jobs:
  generate:
    name: ensure fakes are up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Determine Go Version
        run: |
          GO_VERSION=$(cat src/autoscaler/go.mod | grep -E "^go " | sed 's/go //')
          echo "go-version=${GO_VERSION}" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
           go-version: ${{ env.go-version }}

      - name: Go Build
        run: |
          source .envrc
          pushd src/autoscaler
            make buildtools
            make generate
            git diff
            git status
          popd

      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.12

      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: |
          echo "::error::Fakes are out of date, run make generate to update"
          exit 1
