name: gosub
on:
  pull_request:
jobs:
  generate:
    name: ensure gosub specs are up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine Go Version
        run: |
          GO_VERSION=$(cat src/autoscaler/go.mod | grep -E "^go " | sed 's/go //')
          echo "go-version=${GO_VERSION}" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
           go-version: ${{ env.go-version }}

      - name: Go Build
        run: |
          source .envrc
          ./scripts/sync-package-specs

      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.12

      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: |
          echo "::error::Specs are out of date, run ./scripts/update && ./scripts/sync-package-specs to update"
          exit 1
