---
name: mysql

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
 
jobs:
  mysql:
    strategy:
      matrix:
        go: [1.15.1]
    env:
      DB_DATABASE: autoscaler
      DB_USER: root
      DB_PASSWORD: root
    runs-on: ubuntu-latest
    name: Build golang=${{ matrix.go }}, mysql=latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules: true  

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      
      - name: Maven Build
        run: |
          pushd src/app-autoscaler
            mvn --no-transfer-progress package
          popd

      - name: Setup MySQL
        run: |
          echo -e "[mysqld]\nsql_mode=NO_ENGINE_SUBSTITUTION,STRICT_ALL_TABLES\n[server]\ninnodb_log_file_size=256MB\ninnodb_buffer_pool_size=512MB\nmax_allowed_packet=32MB" | sudo tee -a /etc/mysql/my.cnf
          sudo /etc/init.d/mysql start
          mysql --version
          mysql -e "SET PASSWORD FOR root@localhost='';" -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }}
          pushd src/app-autoscaler
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=src/autoscaler/api/db/api.db.changelog.yml --username=${{ env.DB_USER }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=src/autoscaler/servicebroker/db/servicebroker.db.changelog.json --username=${{ env.DB_USER }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=scheduler/db/scheduler.changelog-master.yaml --username=${{ env.DB_USER }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=scheduler/db/quartz.changelog-master.yaml --username=${{ env.DB_USER }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=src/autoscaler/metricsserver/db/metricscollector.db.changelog.yml --username=${{ env.DB_USER }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=src/autoscaler/eventgenerator/db/dataaggregator.db.changelog.yml --username=${{ env.DB_USER }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=src/autoscaler/scalingengine/db/scalingengine.db.changelog.yml --username=${{ env.DB_USER }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=src/autoscaler/operator/db/operator.db.changelog.yml --username=${{ env.DB_USER }} update
          popd

      - name: Go Build
        run: |
          source .envrc
          pushd src/changeloglockcleaner
            go get github.com/onsi/ginkgo/ginkgo
            ginkgo -r race -randomizeAllSpecs -keepGoing
          popd


