name: Test failing workflows early
on:
  pull_request:
    types: [ opened, labeled, synchronize ]
    paths:
      - 'src/acceptance/**'

jobs:
  job_1:
    name: "Job 1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      - name: "Let the workflow fail"
        run: |
          echo '::set-output name=workflow_conclusion::failure'
          exit 1

  job_2:
    needs: [ job_1 ]
    name: "Job 2 (dependent on Job 1)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      - name: deploy autoscaler
        run: |
          echo 'I succeed always!'
          exit 0